<a href="https://colab.research.google.com/github/asadbek11211/Pandas_exercises/blob/main/05_ml_05_amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 5-MODUL. Machine Learning

### Portfolio uchun vazifa: Toshkent shahrida uylarning narxini aniqlash.

Ushbu amaliyotda sizning vazifangiz berilgan ma`lumotlar asosida Toshkent shahridagi uylarning narxini aniqlash.

# Ustunlar ta'rifi
- `location` - sotilayotgan uy manzili
- `district` - uy joylashgan tuman
- `rooms` - xonalar soni
- `size` - uy maydoni (kv.m)
- `level` - uy joylashgan qavat
- `max_levels` - ja'mi qavatlar soni
- `price` - uy narxi

## Vazifani CRSIP-DM Metolodgiyasi yordamida bajaring.
<img src="https://i.imgur.com/dzZnnYi.png" alt="CRISP-DM" width="800"/>

In [143]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv')
df.sample(5)

location         district  \
6692         город Ташкент, Яшнободский район, Сандикли      Яшнободский   
3182            город Ташкент, Юнусабадский район, Киёт     Юнусабадский   
1341  город Ташкент, Чиланзарский район, Чиланзар 10...     Чиланзарский   
226   город Ташкент, Чиланзарский район, Чиланзар 7-...     Чиланзарский   
6595        город Ташкент, Шайхантахурский район, Хадра  Шайхантахурский   

      rooms size  level  max_levels  price  
6692      3  119      1           5  95000  
3182      2   50      4           4  44000  
1341      2   41      4           4  31000  
226       2   44      3           4  32900  
6595      2   48      8           9  69000

In [144]:
#df["size"] = df["size"].apply(np.int32)
#df[df['price']=='Договорная']
df.drop(df[df.price == 'Договорная'].index, inplace=True)
df["price"] = df["price"].apply(np.int)


<ipython-input-144-0f164f834cc1>:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df["price"] = df["price"].apply(np.int)


In [145]:
df.drop(df[df['size'] == 'Площадьземли:1сот'].index, inplace=True)
df['size'] = df['size'].apply(np.float)

<ipython-input-145-a1e2b9d05560>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df['size'] = df['size'].apply(np.float)


In [146]:
df.rename({'size':'hsize'}, axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7465 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   location    7465 non-null   object 
 1   district    7465 non-null   object 
 2   rooms       7465 non-null   int64  
 3   hsize       7465 non-null   float64
 4   level       7465 non-null   int64  
 5   max_levels  7465 non-null   int64  
 6   price       7465 non-null   int64  
dtypes: float64(1), int64(4), object(2)
memory usage: 466.6+ KB


In [147]:
df['hsize'] = df['hsize'].astype('int')

In [148]:
df.head()

location       district  rooms  \
0  город Ташкент, Юнусабадский район, Юнусабад 8-...   Юнусабадский      3   
1  город Ташкент, Яккасарайский район, 1-й тупик ...  Яккасарайский      2   
2  город Ташкент, Чиланзарский район, Чиланзар 2-...   Чиланзарский      2   
3  город Ташкент, Чиланзарский район, Чиланзар 9-...   Чиланзарский      3   
4  город Ташкент, Чиланзарский район, площадь Актепа   Чиланзарский      3   

   hsize  level  max_levels  price  
0     57      4           4  52000  
1     52      4           5  56000  
2     42      4           4  37000  
3     65      1           4  49500  
4     70      3           5  55000

In [149]:
df.location.unique()

array(['город Ташкент, Юнусабадский район, Юнусабад 8-й квартал',
       'город Ташкент, Яккасарайский район, 1-й тупик Шота Руставели',
       'город Ташкент, Чиланзарский район, Чиланзар 2-й квартал', ...,
       'город Ташкент, Мирзо-Улугбекский район, Кадырдон',
       'город Ташкент, Мирзо-Улугбекский район, Ц-1 кафе Bibigon',
       'город Ташкент, Яшнободский район, Базар Кадышева'], dtype=object)

In [150]:
df.district.unique()

array(['Юнусабадский', 'Яккасарайский', 'Чиланзарский', 'Учтепинский',
       'Мирзо-Улугбекский', 'Яшнободский', 'Мирабадский',
       'Шайхантахурский', 'Олмазорский', 'Сергелийский', 'Янгихаётский',
       'Бектемирский'], dtype=object)

In [151]:
df.isnull().sum()

location      0
district      0
rooms         0
hsize         0
level         0
max_levels    0
price         0
dtype: int64

In [152]:
df1 = df.drop(['location','district'], axis=1)
df1.corrwith(df1.price).sort_values(ascending=False)

price         1.000000
rooms         0.056161
max_levels    0.011175
hsize         0.001107
level        -0.003449
dtype: float64

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7465 entries, 0 to 7564
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   district    7465 non-null   object
 1   rooms       7465 non-null   int64 
 2   hsize       7465 non-null   int64 
 3   level       7465 non-null   int64 
 4   max_levels  7465 non-null   int64 
 5   price       7465 non-null   int64 
dtypes: int64(5), object(1)
memory usage: 408.2+ KB


In [157]:
import numpy as np
import sklearn 

In [160]:
housing_cat = df[['district']]
housing_cat

district
0          Юнусабадский
1         Яккасарайский
2          Чиланзарский
3          Чиланзарский
4          Чиланзарский
...                 ...
7560        Яшнободский
7561        Яшнободский
7562    Шайхантахурский
7563  Мирзо-Улугбекский
7564       Чиланзарский

[7465 rows x 1 columns]

 ML algoritmlar sonlar bilan ishlaydi. Shuning uchun bu ustunni ham sonlarga o'zgartirishimiz kerak. 

 Buning 2 usuli bor:
1. Har bir matnni son bilan almashtirish.

Buning uchun sklearn tarkibida `OrdinalEncoder`dan foydalanamiz:

In [161]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)
housing_cat_encoded

array([[8.],
       [9.],
       [6.],
       ...,
       [7.],
       [2.],
       [6.]])

2. `OneHotEncoder` - usuli yordamida har bir noyob qiymat alohida ustunga aylanadi va mos keluvchi ustunga 1, qolganlariga 0 qo'yiladi. Tushunarli bo'lishi uchun keyingi kodga ahamiyat bering.

In [162]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Ma'lumotlarni train va test setga ajratamiz

In [163]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

x_train = train_set.drop('price', axis=1)
y = train_set['price'].copy()

x_num = x_train.drop(['district'], axis=1) 

In [164]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5972 entries, 436 to 7368
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   district    5972 non-null   object
 1   rooms       5972 non-null   int64 
 2   hsize       5972 non-null   int64 
 3   level       5972 non-null   int64 
 4   max_levels  5972 non-null   int64 
dtypes: int64(4), object(1)
memory usage: 279.9+ KB


In [165]:
x_train.rooms.unique()

array([ 2,  1,  4,  3,  5,  6,  7,  8, 10])

In [166]:
x_train.hsize.unique()

array([   60,    30,   122,    62,    52,    38,   153,    93,    63,
          46,    50,    17,    36,    84,   185,    20,    90,    80,
          41,    53,   130,    96,    54,   100,    48,   115,    35,
          45,    55,    58,    51,    56,    42,   187,    72,    95,
          16,   110,    75,    82,   120,    61,    70,    78,   160,
         139,    47,    39,    87,    28,    94,    44,    33,    65,
          68,   113,    57,    24,    88,    77,    92,   112,    64,
         140,    98,     5,    34,   135,    74,    67,    27,    40,
          18,    29,    66,   180,    59,   105,   118,   132,   117,
          14,   347,    49,   124,   101,    73,   106,    85,    71,
          22,    86,    43,   107,    76,   145,    26,   119,   205,
         125,   183,   170,   252,    32, 69000,    91,    83,   210,
          97,   200,   172,    37,    69,   230,    23,   103,    31,
         320,   147,   167,    79,   129,   211,   150,   165,   215,
         111,    25,

In [167]:
x_train.level.unique()

array([ 4,  1,  3,  2,  5,  6,  8, 10,  7,  9, 12, 16, 13, 11, 15, 14, 19,
       18])

In [168]:
x_train.max_levels.unique()

array([ 4,  2,  5,  9,  8,  3, 12,  6,  7, 16, 11, 22, 10, 18, 13, 25, 17,
        1, 23, 20, 19])

# Sonli ustunlar un Pipeline 

In [169]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

num_pipeline = Pipeline([
    ('std_scaler', StandardScaler())
])


# Matinli ustunlar uchun

In [170]:
from sklearn.compose import ColumnTransformer

num_attribs = list(x_num)
cat_attribs = ['district']

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs),
    ('cat', OneHotEncoder(), cat_attribs)
]) 

Mana yakuniy, to'liq konveyer tayyor bo'ldi (`full_pipeline`). 

Konveyerni ishga tushirish uchun `.fit_transform()` metodini chaqrisih kifoya.

In [171]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5972 entries, 436 to 7368
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   district    5972 non-null   object
 1   rooms       5972 non-null   int64 
 2   hsize       5972 non-null   int64 
 3   level       5972 non-null   int64 
 4   max_levels  5972 non-null   int64 
dtypes: int64(4), object(1)
memory usage: 279.9+ KB


In [172]:
x_prepared = full_pipeline.fit_transform(x_train)

In [173]:
x_prepared

array([[-0.57458889, -0.03522529,  0.12524471, ...,  0.        ,
         0.        ,  0.        ],
       [-1.4952878 , -0.05654452, -1.20092799, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.26680894,  0.00883446, -0.31681286, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.34611002, -0.01106349, -0.75887042, ...,  0.        ,
         0.        ,  0.        ],
       [-0.57458889, -0.04446362,  0.12524471, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.26680894, -0.01106349, -0.75887042, ...,  0.        ,
         0.        ,  1.        ]])

### Machine Learning

Bizning maqsadimiz bashorat qilish, buning uchun bir nechta ML algoritmlar mavjud.

Biz kelgusi darslarda ularning har biri bilan yaqinda tanishamiz, hozir esa scikit-learn tarkibidagi ba'zi tayyor algoritmlardan foydalanamiz.

#### Linear Regression - Chiziqli regressiya
`sklearn` tarkibidagi `LinearRegression` klassidan yangi model yaratamiz.

In [174]:
from sklearn.linear_model import LinearRegression

LR_model = LinearRegression()

`LinearRegression` bu estimator. Estimatorlar ma'lumotlarni qabul qilib oladi va `.fit()` metodi yordamida ulardan bashorat qilishni _o'rganadi_ (machine _learning_)

In [175]:
LR_model.fit(x_prepared, y)


LinearRegression()

**TAMOM!** Machine Learning tugadi! Ha, adashmadingiz, bor yo'g'i 3 qator kod bilan biz hozirgina kompyuterga uylarni narxini bashorat qilishni o'rgatdik.

Modelni qanday qilib tekshirib ko'rishimiz mumkin? Keling `housing` datasetdan biror qatorni modelga beramiz va chiqqan natijani bizdagi bor natija (label) bilan solishtiramiz.

In [176]:
test_data = x_train.sample(5)
test_data

district  rooms  hsize  level  max_levels
6928       Чиланзарский      2     62      8           9
1631      Яккасарайский      3     75      2           4
4723        Мирабадский      2     62      9           9
3954  Мирзо-Улугбекский      3     94     16          23
7495        Яшнободский      3     64      4           5

In [177]:
test_label = y.loc[test_data.index]
test_label

6928     37000
1631     55000
4723     46000
3954    118000
7495     35000
Name: price, dtype: int64

`test_data` ni pipelinedan o'tkazib, bizga kerak ko'rinishga keltirib olamiz.

**Ahamiyat bering** bu safgar biz `.transform()` metodini chaqiramiz, sababi `.fit()` metodini avval chaqirgan edik.

In [178]:
test_data_prepared = full_pipeline.transform(test_data)
test_data_prepared

array([[-0.57458889, -0.033804  ,  1.89347497,  1.11704692,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.34611002, -0.02456567, -0.75887042, -0.78114458,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.57458889, -0.033804  ,  2.33553253,  1.11704692,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.34611002, -0.01106349,  5.42993549,  6.4319831 ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.34611002, -0.03238272,  0

In [179]:
# Bashorat qilamiz
predicted_data = LR_model.predict(test_data_prepared)
predicted_data

array([37931.21526975, 77391.68636673, 66806.68172792, 82204.53207192,
       61293.38321142])

Yuoqirda ko'rib turganingiz bashorat qilingan qiymatlar. Xo'sh, ular real qiymatlardan qanday farq qiladi, solishtiramiz:

In [180]:
pd.DataFrame({'Prognoz':predicted_data, 'Real baxosi': test_label})

Prognoz  Real baxosi
6928  37931.215270        37000
1631  77391.686367        55000
4723  66806.681728        46000
3954  82204.532072       118000
7495  61293.383211        35000

# Modelni baxolaymiz

In [181]:
test_set

district  rooms  hsize  level  max_levels  price
2301      Яшнободский      3     86      4           9  89000
6126      Учтепинский      3     70      2           5  43500
2149    Яккасарайский      3     90      5           5  45000
5594     Чиланзарский      1     36      2           4  24700
6566      Учтепинский      4    100      1           4  87000
...               ...    ...    ...    ...         ...    ...
6593  Шайхантахурский      3     80      6           9  48000
4089  Шайхантахурский      6    500      2           2   1800
441      Чиланзарский      1     36      2           5  28500
5639  Шайхантахурский      3     70      6           7  60000
2538      Мирабадский      2     48      3           5  42000

[1493 rows x 6 columns]

Avval predictor ustunlarni ajratib olaylik (`median_house_value`) dan boshqa barcha ustunlar):

In [182]:
x_test = test_set.drop('price', axis=1)
x_test

district  rooms  hsize  level  max_levels
2301      Яшнободский      3     86      4           9
6126      Учтепинский      3     70      2           5
2149    Яккасарайский      3     90      5           5
5594     Чиланзарский      1     36      2           4
6566      Учтепинский      4    100      1           4
...               ...    ...    ...    ...         ...
6593  Шайхантахурский      3     80      6           9
4089  Шайхантахурский      6    500      2           2
441      Чиланзарский      1     36      2           5
5639  Шайхантахурский      3     70      6           7
2538      Мирабадский      2     48      3           5

[1493 rows x 5 columns]

Label (`median_house_value`) ustunini ajratib olamiz.

In [183]:
y_test = test_set['price'].copy()
y_test

2301    89000
6126    43500
2149    45000
5594    24700
6566    87000
        ...  
6593    48000
4089     1800
441     28500
5639    60000
2538    42000
Name: price, Length: 1493, dtype: int64

`test_set` ni ham pipelinedan o'tkazamiz:

In [184]:
x_test_prepared = full_pipeline.transform(x_test)

Bashoratlash

In [185]:
y_predicted = LR_model.predict(x_test_prepared)

# Bashorat va real datani solishtirish uchun avvalgi bo'limda ko'rgan Root mean square error (RMSE) dan foydalanamiz:

In [186]:
from sklearn.metrics import mean_squared_error
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

1366742.755665623


## Modelni saqlash

Yaratgan modelimizdan kelajakda foydalanish uchun saqlab qo'yishimiz lozim. Umuman olganda nafaqat model, balki boshqa kerak bo'ladigan o'zgaruvchilarni ham saqlab qo'yish maqsadga muvvofiq bo'ladi. Masalan pipeline.

Buning uchun Pythondagi `pickle` yoki `joblib` modullaridan foydalanamiz.

### `pickle` yordamida saqlash

In [187]:
import pickle

filename = 'LR_model.pkl' # faylga istalgan nom beramiz
with open(filename, 'wb') as file:
    pickle.dump(LR_model, file)

# This is my first ML work

---

